server:
  port: 8080

  #SSL
#  ssl:
#    enabled: true
#    key-store: /home/ubuntu/agmscare/agmscare_kr.jks
#    key-store-type: JKS
#    key-store-password: uxnsw0214 # jks 또는 pfx 암호
#    key-alias: agmscare_kr

spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/agms?useSSl=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Pa$$w0rd

    hikari:
      maximum-pool-size: 20
      auto-commit: false

  sql:
    init:
      mode: always

  # Session
  session:
    store-type: jdbc

  jpa:
    hibernate:
      ddl-auto: 'validate'
    show-sql: true
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true
          plan_parameter_metadata_max_size: 128
          plan_cache_max_size: 2048
        format_sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    database: postgresql  #mysql

  mail:
    #    host: smtp.gmail.com
    username: agms@uxn.co.kr
    password: uthfkglqvwpayxqw
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enabled: true
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
          ssl:
            enabled: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

logging:
  file:
    name: ${user.dir}/log/event-check.log # 로깅 파일 위치
    max-history: 7 # 로그 파일 삭제 주기 7일 후 로그 삭제.
    max-size: 10MB # 로그 파일 하나당 최대 파일 사이즈
  level:
    com.example : debug #debug -> info -> error


